### ISSUE TITLE
Make types more portable

### ISSUE THREAD

**Issue by callstackexceed** [NorthernOceanS/norma-core#28]

**Comment by dzx-dzx** [comment]
The NC-flavored generic types serve the purpose of providing developers with a unified interface for interacting(creating, modifying, transforming, and exporting) with data involved in the generation and construction, namely **BlockType** and **Position**.

**Comment by dzx-dzx** [comment]
## `BlockType`
In MC, there are two coexisting forms that descript the property of a certain block, **`blockstate`**(an object) and **`tiledata`**(an integer). It is expected that, `BlockType` can mask both types, but developers can fetch the original form of data at will.
### ``

**Comment by callstackexceed** [comment]
related to <https://github.com/NorthernOceanS/NormaConstructor/issues/40>

**Comment by dzx-dzx** [comment]
## `BlockType`
In MC, there are two coexisting forms(hereinafter referred as "original forms") that descript the properties of a certain block, **`blockstate`**(an object) and **`tiledata`**(an integer). It is expected that, `BlockType` can mask both types, but developers can fetch either original form at will. To do this, internally the two types should be able to convert to each other, which entails the inclusion of [block.js](https://github.com/WavePlayz/Bedrock-Scripting-API/tree/master/utility/getBlockDetails)
### Create
#### `BlockType.fromBlockstate(blockIdentifier,blockstate)`
Returns the corresponding `blockType`
#### `BlockType.fromTiledata(blockIdentifier,tiledata)`
Returns the corresponding `blockType`
### Get
Both ofthe original forms can be obtained through the following methods, even if but one is provided during the creation.
#### `BlockType.prototype.blockIdentifier`
A `getter` that returns the `blockIdentifier`(i.e. the name of the block).
#### `BlockType.prototype.blockstate`
A `getter` that returns the `blockstate`.
#### `BlockType.prototype.tiledata`
A `getter` that returns the `tiledata`.
#### `BlockType.prototype.listAvailableBlockstates`
Returns an array that contains all available `blockstate`s for this `blockType`, judging from the `blockIdentifier`.
#### `BlockType.listAvailableBlockIdentifiers`
Returns an array that contains all available `blockIdentifier`s.
### Set
#### `BlockType.prototype.blockIdentifier`
A `setter` that sets the `blockIdentifier`. A validation will be performed, and an exception *exception_name_needed* will be thrown if the `blockIdentifier` doesn't exist. `Blockstate` or `tiledate` will be erased after the operation, if successful.
#### `BlockType.prototype.blockstate`
A `setter` that sets the `blockstate`. A validation will be performed, and an exception *exception_name_needed* will be thrown if such cannot be applied.
#### `BlockType.prototype.tiledata`
A `setter` that sets the `tiledata`. A validation will be performed, and an exception *exception_name_needed* will be thrown if such cannot be applied.

## `Position`
Consisting of `coordinate` and `dimension`
### `Coordinate`
| Name | Type     |
| ---- | -------- |
| x    | Number  |
| y    | Number  |
| z    | Number |
#### `Coordinate.prototype.x`,`Coordinate.prototype.y``Coordinate.prototype.z`
~~Both a getter and a setter.~~
#### `Coordinate.prototype.add(coordinate)`,`Coordinate.prototype.add({x,y,z})`
A function that respectively adds x,y,z to the object it belongs to.
### `dimension`
A `String` literal, can be `overworld`, `nether`, or `the_end`
## `Direction`
| Name | Type   | 
| ---- | ------ | 
| x    | Number | 
| y    | Number |
